package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultAt_the_back <br>
 * @version generated on Sat May 16 15:18:49 CEST 2020 by kamsz
 */
public class DefaultAt_the_back extends WrappedIndividualImpl implements At_the_back {

    public DefaultAt_the_back(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
