package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTo_left <br>
 * @version generated on Sat May 16 15:18:50 CEST 2020 by kamsz
 */
public class DefaultTo_left extends WrappedIndividualImpl implements To_left {

    public DefaultTo_left(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
