package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIn_the_front <br>
 * @version generated on Sun May 17 23:43:01 CEST 2020 by kamsz
 */
public class DefaultIn_the_front extends WrappedIndividualImpl implements In_the_front {

    public DefaultIn_the_front(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
