package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultTraffic_code <br>
 * @version generated on Sun May 17 12:58:33 CEST 2020 by kamsz
 */
public class DefaultTraffic_code extends WrappedIndividualImpl implements Traffic_code {

    public DefaultTraffic_code(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://webprotege.stanford.edu/traffic_code_has
     */
     
    public Collection<? extends Traffic_type> getTraffic_code_has() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_TRAFFIC_CODE_HAS,
                                               DefaultTraffic_type.class);
    }

    public boolean hasTraffic_code_has() {
	   return !getTraffic_code_has().isEmpty();
    }

    public void addTraffic_code_has(Traffic_type newTraffic_code_has) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_TRAFFIC_CODE_HAS,
                                       newTraffic_code_has);
    }

    public void removeTraffic_code_has(Traffic_type oldTraffic_code_has) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_TRAFFIC_CODE_HAS,
                                          oldTraffic_code_has);
    }


}
