package project.impl;

import project.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultIn_a_vehicle <br>
 * @version generated on Sat May 16 15:18:49 CEST 2020 by kamsz
 */
public class DefaultIn_a_vehicle extends WrappedIndividualImpl implements In_a_vehicle {

    public DefaultIn_a_vehicle(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





}
