package project;

import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Suspended_sentence <br>
 * @version generated on Sat May 16 15:18:50 CEST 2020 by kamsz
 */

public interface Suspended_sentence extends Restriction_of_liberty {

    /* ***************************************************
     * Property http://webprotege.stanford.edu/has_type_of_sentence
     */
     
    /**
     * Gets all property values for the has_type_of_sentence property.<p>
     * 
     * @returns a collection of values for the has_type_of_sentence property.
     */
    Collection<? extends WrappedIndividual> getHas_type_of_sentence();

    /**
     * Checks if the class has a has_type_of_sentence property value.<p>
     * 
     * @return true if there is a has_type_of_sentence property value.
     */
    boolean hasHas_type_of_sentence();

    /**
     * Adds a has_type_of_sentence property value.<p>
     * 
     * @param newHas_type_of_sentence the has_type_of_sentence property value to be added
     */
    void addHas_type_of_sentence(WrappedIndividual newHas_type_of_sentence);

    /**
     * Removes a has_type_of_sentence property value.<p>
     * 
     * @param oldHas_type_of_sentence the has_type_of_sentence property value to be removed.
     */
    void removeHas_type_of_sentence(WrappedIndividual oldHas_type_of_sentence);


    /* ***************************************************
     * Property http://webprotege.stanford.edu/criminal_sentence_properties
     */
     
    /**
     * Gets all property values for the criminal_sentence_properties property.<p>
     * 
     * @returns a collection of values for the criminal_sentence_properties property.
     */
    Collection<? extends Object> getCriminal_sentence_properties();

    /**
     * Checks if the class has a criminal_sentence_properties property value.<p>
     * 
     * @return true if there is a criminal_sentence_properties property value.
     */
    boolean hasCriminal_sentence_properties();

    /**
     * Adds a criminal_sentence_properties property value.<p>
     * 
     * @param newCriminal_sentence_properties the criminal_sentence_properties property value to be added
     */
    void addCriminal_sentence_properties(Object newCriminal_sentence_properties);

    /**
     * Removes a criminal_sentence_properties property value.<p>
     * 
     * @param oldCriminal_sentence_properties the criminal_sentence_properties property value to be removed.
     */
    void removeCriminal_sentence_properties(Object oldCriminal_sentence_properties);



    /* ***************************************************
     * Property http://webprotege.stanford.edu/judgement_passing_date
     */
     
    /**
     * Gets all property values for the judgement_passing_date property.<p>
     * 
     * @returns a collection of values for the judgement_passing_date property.
     */
    Collection<? extends Object> getJudgement_passing_date();

    /**
     * Checks if the class has a judgement_passing_date property value.<p>
     * 
     * @return true if there is a judgement_passing_date property value.
     */
    boolean hasJudgement_passing_date();

    /**
     * Adds a judgement_passing_date property value.<p>
     * 
     * @param newJudgement_passing_date the judgement_passing_date property value to be added
     */
    void addJudgement_passing_date(Object newJudgement_passing_date);

    /**
     * Removes a judgement_passing_date property value.<p>
     * 
     * @param oldJudgement_passing_date the judgement_passing_date property value to be removed.
     */
    void removeJudgement_passing_date(Object oldJudgement_passing_date);



    /* ***************************************************
     * Property http://webprotege.stanford.edu/restriction_of_liberty_length_years
     */
     
    /**
     * Gets all property values for the restriction_of_liberty_length_years property.<p>
     * 
     * @returns a collection of values for the restriction_of_liberty_length_years property.
     */
    Collection<? extends Integer> getRestriction_of_liberty_length_years();

    /**
     * Checks if the class has a restriction_of_liberty_length_years property value.<p>
     * 
     * @return true if there is a restriction_of_liberty_length_years property value.
     */
    boolean hasRestriction_of_liberty_length_years();

    /**
     * Adds a restriction_of_liberty_length_years property value.<p>
     * 
     * @param newRestriction_of_liberty_length_years the restriction_of_liberty_length_years property value to be added
     */
    void addRestriction_of_liberty_length_years(Integer newRestriction_of_liberty_length_years);

    /**
     * Removes a restriction_of_liberty_length_years property value.<p>
     * 
     * @param oldRestriction_of_liberty_length_years the restriction_of_liberty_length_years property value to be removed.
     */
    void removeRestriction_of_liberty_length_years(Integer oldRestriction_of_liberty_length_years);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
